# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  google_oauth_client_id: 70921055603-d0nacjicr48usjqpcn5skuknbuejjedp.apps.googleusercontent.com
  google_oauth_secret_key: NAcPE5Gu8eq5bbIe6nhMQAaC

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7055cd5a7383a21060409dbc24070c887884e1e278088e52b872c194ba9d8a3831068facc9cd1e197a17224435cbf5876f9a742587251913f099a63b4536e02b

test:
  secret_key_base: 9c3dc118dd877c53fde75091577bc376a7943a2af3bc63f470dd3a4722f918bbe6bb2d1d3da3ac175e8b347ea6a20f46d44a6bfec7afc26c86150ca441e47c3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # secret_key_base: 9c3dc118dd877c53fde75091577bc376a7943a2af3bc63f470dd3a4722f918bbe6bb2d1d3da3ac175e8b347ea6a20f46d44a6bfec7afc26c86150ca441e47c3f
